### ISSUE TITLE
Field defines a relation with model 'Tag', which is either not installed, or is abstract

### ISSUE THREAD

**Issue by ljsalvatierra** [pigmonkey/django-wishlist#1]
Performing system checks...

Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7fe82631c620>
Traceback (most recent call last):
  File "/home/ljsalvatierra/bin/anaconda3/envs/django3/lib/python3.5/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(_args, *_kwargs)
  File "/home/ljsalvatierra/bin/anaconda3/envs/django3/lib/python3.5/site-packages/django/core/management/commands/runserver.py", line 121, in inner_run
    self.check(display_num_errors=True)
  File "/home/ljsalvatierra/bin/anaconda3/envs/django3/lib/python3.5/site-packages/django/core/management/base.py", line 420, in check
    raise SystemCheckError(msg)
django.core.management.base.SystemCheckError: SystemCheckError: System check identified some issues:

ERRORS:
wishlist.Item.tags: (fields.E300) Field defines a relation with model 'Tag', which is either not installed, or is abstract.

System check identified 1 issue (0 silenced).

**Comment by ljsalvatierra** [comment]
You have to reference 'taggit' in your project 'INSTALLED_APPS

**Comment by dev-aniket90** [comment]
Thanks a lot

**Comment by HelloMukama** [comment]
Thanks

**Comment by Ebikakpou** [comment]
Thanks a lot, i came across this error too, at first i was dumbfounded, i never knew I would find the solution in the net, i really apreaciate it.

**Comment by amithuu** [comment]
i have added my app in Installed Apps still raising the same error, but there i am trying to get the data from another database, is thats config is the problem,,
